### ISSUE TITLE
Missing system apps on iPad Air 2 iOS 9.3.5

### ISSUE THREAD

**Issue by cs59** [GeoSn0w/Blizzard-Jailbreak-9#2]
So, am sure you know me on Twitter, but I just got an unexpected issue in my iPad 2 iOS 9.3.5
Steps to reproduce the error:
Sideloaded the BLIZZARD iPA
Opened and Clicked Jailbreak and jailbroken at first click, after that apple logo and boot to Jailbroken state, then opened cydia and cydia started preparing system then again apple logo and booted then opened cydia and 12 upgrades was available, so I clicked upgrade and after upgrade I click Restart Springboard and after that it stuck on respring like black screen and after 1 minute it turned screen to black fully, then I click on power button and slide to unlock then I seen all system apps gone except appstore apps.
![9C630798-A8EC-403C-90D2-1C849C32C784](https://user-images.githubusercontent.com/68501788/181915375-f87b4493-87c4-4730-b6ba-da157dac1ea0.jpeg)
![3DC9651F-31AF-41E4-87E4-904F1517E237](https://user-images.githubusercontent.com/68501788/181915359-b9b64251-6bc3-4061-a081-4ac962b4c9a9.jpeg)

**Comment by GeoSn0w** [comment]
Thank you for the report, were you jailbroken before with Phoenix, Polaris or other such jb?

**Comment by GeoSn0w** [comment]
Preparing file system on Cydia should not actually happen, it should be blocked by .cydia_no_stash file. If it did for you, something removed .cydia_no_stash from your system. I wonder if you used any other jb before. Will push an update to Blizzard to enforce the file.

**Comment by cs59** [comment]
> Preparing file system on Cydia should not actually happen, it should be blocked by .cydia_no_stash file. If it did for you, something removed .cydia_no_stash from your system. I wonder if you used any other jb before. Will push an update to Blizzard to enforce the file.

No, the iPad is already freshly restored and keeped turned off lol, just freshly jailbreak

**Comment by GeoSn0w** [comment]
I've just pushed a fix that ensures .cydia_no_stash is created. Will compile and provide an IPA soon. Thanks for your patience.

**Comment by GeoSn0w** [comment]
@cs59 can you try this IPA? https://github.com/GeoSn0w/Blizzard-Jailbreak-9/releases/tag/v1.1

**Comment by cs59** [comment]
> @cs59 can you try this IPA? https://github.com/GeoSn0w/Blizzard-Jailbreak-9/releases/tag/v1.1

Ok let me try

**Comment by cs59** [comment]
> @cs59 can you try this IPA? https://github.com/GeoSn0w/Blizzard-Jailbreak-9/releases/tag/v1.1

Ok tested this ipa and working very fine and stable, thnx for the help.
PS: The iPad is usuable now lol

**Comment by GeoSn0w** [comment]
Thank you so much for testing. Will mark this as finished.
