### ISSUE TITLE
Error like this

### ISSUE THREAD

**Issue by ganimine** [GeoSn0w/Blizzard-Jailbreak-9#6]
Sideloadly version 0.26.6, Darwin 10.13, amd64
Using IPA file: /Users/vedha_ios/Downloads/Blizzard.Jailbreak.v1.3.ipa: 087230ef3c3f880a91afc41d4f01f94c
Will use Local Anisette
Checking iOS version...
iOS version 9.3.5, will not mangle bundleID
Obtaining team ID
Using team "GANESH KOYYALA" (Individual) with id YJXC37JM5K
Making sure device ID bc557048bf8491ec70775250affb17058eb3cab6 is registered
Device bc557048bf8491ec70775250affb17058eb3cab6 is already registered
Checking private key
Looking up app ID
Registered dummy app ID 23D3R8YLUY
Signing...
Connecting...
FAILED: Call to lockdownd_start_service failed: LOCKDOWN_E_INVALID_SERVICE
ERROR: Guru Meditation 89ea16@132:84354a@217:84354a@597:84354a@648:2d2436@179:2d2436@170:2d2436@99:f11511 Call to lockdownd_start_service failed: LOCKDOWN_E_INVALID_SERVICE

**Comment by GeoSn0w** [comment]
The device is likely not activated or the PC is not trusted.
